In [26]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
from sklearn.pipeline import Pipeline
from sklearn.datasets import fetch_mldata
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LinearRegression
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.grid_search import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn import preprocessing

from sklearn import metrics
from sklearn.metrics import classification_report


In [62]:
#row count for processing
row_count = 100000
train_data = np.genfromtxt ('train.csv', delimiter=",", max_rows=row_count, skip_header=True)

#split training label
train_labels = np.asarray([int(numeric_string) for numeric_string in train_data[:,5]])

#split training data
train_data = train_data[:,1:5]

raw_test_labels = np.genfromtxt ('sample_submission.csv', delimiter=",", max_rows=row_count, skip_header=True, dtype=np.character)
test_data = np.genfromtxt ('test.csv', delimiter=",", max_rows=row_count, skip_header=True)
test_data = test_data[:,1:5]
print "Training data shape: ",train_data.shape
print "Training labels shape: ", train_labels.shape
print
print "Training Data: ",train_data[:5,]
print "Training Labels: ",train_labels[:5,]
print

print "Test Data: ",test_data[:5,]

#Format test labels
test_labels = np.zeros((len(raw_test_labels), 4))
for ii in range(len(raw_test_labels)):
    split = str(raw_test_labels[ii,1]).split()
    test_labels[ii,0] = int(raw_test_labels[ii,0])
    test_labels[ii,1] = int(split[0])
    test_labels[ii,2] = int(split[1])
    test_labels[ii,3] = int(split[2])
test_label_1 = np.asarray([int(numeric_string) for numeric_string in test_labels[:,1]])
test_label_2 = np.asarray([int(numeric_string) for numeric_string in test_labels[:,2]])
test_label_3 = np.asarray([int(numeric_string) for numeric_string in test_labels[:,3]])
print "Test Labels: ",test_label_1[:5,]

Training data shape:  (100000L, 4L)
Training labels shape:  (100000L,)

Training Data:  [[  7.94100000e-01   9.08090000e+00   5.40000000e+01   4.70702000e+05]
 [  5.95670000e+00   4.79680000e+00   1.30000000e+01   1.86555000e+05]
 [  8.30780000e+00   7.04070000e+00   7.40000000e+01   3.22648000e+05]
 [  7.36650000e+00   2.51650000e+00   6.50000000e+01   7.04587000e+05]
 [  4.09610000e+00   1.13070000e+00   3.10000000e+01   4.72130000e+05]]
Training Labels:  [8523065625 1757726713 1137537235 6567393236 7440663949]

Test Data:  [[  1.67500000e-01   1.36080000e+00   1.07000000e+02   9.30883000e+05]
 [  7.39090000e+00   2.53010000e+00   3.50000000e+01   8.93017000e+05]
 [  8.09780000e+00   2.34730000e+00   6.20000000e+01   9.76933000e+05]
 [  9.99000000e-01   1.05910000e+00   6.20000000e+01   9.07285000e+05]
 [  6.67000000e-01   9.72540000e+00   4.00000000e+01   9.14399000e+05]]
Test Labels:  [3073560757 1652178628 4894407065 7272466660 4720452725]


In [63]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(train_data, train_labels)
y_pred = knn.predict(test_data)
print "Accuracy for 1st choice", metrics.f1_score(test_label_1, y_pred)
print "Accuracy for 2nd choice", metrics.f1_score(test_label_2, y_pred)
print "Accuracy for 3rd choice", metrics.f1_score(test_label_3, y_pred)
for ii in range(len(y_pred)):
    if y_pred[ii] != test_labels_1[ii]:
        print "Text: %s, actual: %s, predicted %s"%(test_data[ii], test_labels_1[ii]), y_pred[ii])





Accuracy for 1st choice 7.2020886057e-09
Accuracy for 2nd choice

C:\Company\Software\anaconda\lib\site-packages\sklearn\metrics\classification.py:756: DeprecationWarning: The default `weighted` averaging is deprecated, and from version 0.18, use of precision, recall or F-score with multiclass or multilabel data or pos_label=None will result in an exception. Please set an explicit value for `average`, one of (None, 'micro', 'macro', 'weighted', 'samples'). In cross validation use, for instance, scoring="f1_weighted" instead of scoring="f1".
  sample_weight=sample_weight)
C:\Company\Software\anaconda\lib\site-packages\sklearn\metrics\classification.py:756: DeprecationWarning: The default `weighted` averaging is deprecated, and from version 0.18, use of precision, recall or F-score with multiclass or multilabel data or pos_label=None will result in an exception. Please set an explicit value for `average`, one of (None, 'micro', 'macro', 'weighted', 'samples'). In cross validation use, for instance, scoring="f1_weighted" instead of scoring="f1".
  sampl

 1.80057618438e-09
Accuracy for 3rd choice 3.20099230762e-09


C:\Company\Software\anaconda\lib\site-packages\sklearn\metrics\classification.py:756: DeprecationWarning: The default `weighted` averaging is deprecated, and from version 0.18, use of precision, recall or F-score with multiclass or multilabel data or pos_label=None will result in an exception. Please set an explicit value for `average`, one of (None, 'micro', 'macro', 'weighted', 'samples'). In cross validation use, for instance, scoring="f1_weighted" instead of scoring="f1".
  sample_weight=sample_weight)
